// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  template = 1,
  Element = 2,
  Slot = 3,
  DependencyLabel = 4,
  Label = 5,
  Role = 6,
  Index = 7,
  Function = 8,
  Fname = 9,
  Args = 10,
  Interpolation = 11,
  String = 12,
  LexemeOrString = 13,
  Punctuation = 14
