// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "%vQVQPOOOOQO'#Ci'#CiOOQO'#Cj'#CjOOQO'#C}'#C}ObQQO'#C^OOQO'#C^'#C^OOQO'#Ck'#CkQVQPOOOjQQO'#CbO!OQQO'#CaO!ZQQO'#C`O!cQQO'#CdOOQO'#Cv'#CvO!kQQO'#C_OOQO'#C_'#C_O!pQQO,58xOOQO-E6i-E6iO!uQSO,58{O!zQQO,58zO#PQQO,59OOOQO,59O,59OO#PQQO,58yOOQO1G.d1G.dOOQO'#Cc'#CcOOQO1G.g1G.gOOQO'#Cb'#CbOOQO1G.f1G.fO#XQQO'#CeO#jQQO'#CxOOQO'#Cf'#CfO#rQQO1G.jOOQO1G.e1G.eO#PQQO'#ClO#wQQO,59dOOQO7+$U7+$UOOQO,59W,59WOOQO-E6j-E6j",
  stateData: "$P~OcOS~OdSOrPOsQO~O[[OeWO~OfUXhUXiUXkXXoXXpZX~OfaOhTXiTX~OhbOiSX~OkcOodO~OieO~OpfO~OggO~OeiO~O[[OekO~OkXXmZXnZXoXXpZX~OmpOnlX~OnrO~OmpOnla~O",
  goto: "#`rPPswz}!T!X![!b!h![P!k!k!o!uPPPPPPPPP!{P#XPPPP#[TUOVR_SR]SQYSRjbTXSbRhaX[ScepXZScepRncTROVQVOR`VQqlRtqQ^SQlcQoeRspRmcTTOV",
  nodeNames: "⚠ template Element Slot DependencyLabel Label Role Index Function Fname Args Interpolation String LexemeOrString Punctuation",
  maxTerm: 35,
  skippedNodes: [0],
  repeatNodeCount: 2,
  tokenData: "4Y~R!hOX%mXY+xYZ+xZ]%m]^+x^p%mpq+xqr+}rs-Qst+}tu%muv+}vw+}wx+}xy.Tyz.dz{+}{|%m|}.k}!O+}!O!P+}!P!Q+}!Q![.r![!]1{!]!^+}!^!_2S!_!`%m!`!a+}!a!b+}!b!c+}!c!}%m!}#O+}#O#P%m#P#Q+}#Q#R+}#R#S2Z#S#T+}#T#o%m#o#p2b#p#q+}#q#r2g#r#s+}#s$g%m$g$h+}$h$q%m$q$r+}$r$}%m$}%O+}%O%R%m%R%S+}%S%V%m%V%W+}%W$Ig%m$Ig$Ih+}$Ih$Ii+}$Ii$In%m$In$Io+}$Io$Ir%m$Ir$Is+}$Is$JW%m$JW$JX+}$JX$JY+}$JY&Fb%m&Fb&Fc+}&Fc&Fd+}&Fd&Fe+}&Fe&Ff+}&Ff;'S%m;'S;=`+r<%lO%mR%t!OeQrPOX%mZ]%m^p%mqr(tst(ttu%mux(tz{(t{|%m}!Q(t!Q![%m!]!^(t!_!`%m!`!c(t!c!}%m!}#O(t#O#P%m#P#R(t#S#T(t#T#o%m#p#q(t#q#r){#r#s(t#s$g%m$g$h(t$h$q%m$q$r(t$r$}%m$}%O(t%O%R%m%R%S(t%S%V%m%V%W(t%W$Ig%m$Ig$Ii(t$Ii$In%m$In$Io(t$Io$Ir%m$Ir$Is(t$Is$JW%m$JW$JY(t$JY&Fb%m&Fb&Ff(t&Ff;'S%m;'S;=`+r<%lO%mQ(y^eQOX(tZ](t^p(tqr(tsx(tz|(t}![(t!]!^(t!_#R(t#S#o(t#p#q(t#r;'S(t;'S;=`)u<%lO(tQ)xP;=`<%l(tP*QhrPOX){Z]){^p){tu){{|){!Q![){!_!`){!c!}){#O#P){#T#o){#q#r){#s$g){$h$q){$r$}){%O%R){%S%V){%W$Ig){$Ii$In){$Io$Ir){$Is$JW){$JY&Fb){&Ff;'S){;'S;=`+l<%lO){P+oP;=`<%l){R+uP;=`<%l%m~+}Oc~R,U^eQsPOX(tZ](t^p(tqr(tsx(tz|(t}![(t!]!^(t!_#R(t#S#o(t#p#q(t#r;'S(t;'S;=`)u<%lO(tR-VTsPOr-frs-xs;'S-f;'S;=`-}<%lO-fQ-iTOr-frs-xs;'S-f;'S;=`-}<%lO-fQ-}O[QQ.QP;=`<%l-fR.[PkQsPyz._Q.dOoQR.kOnQsPR.rOmQsPV.{!OeQgSrPOX%mZ]%m^p%mqr(tst(ttu%mux(tz{(t{|%m}!Q(t!Q![.r!]!^(t!_!`%m!`!c(t!c!}%m!}#O(t#O#P%m#P#R(t#S#T(t#T#o%m#p#q(t#q#r){#r#s(t#s$g%m$g$h(t$h$q%m$q$r(t$r$}%m$}%O(t%O%R%m%R%S(t%S%V%m%V%W(t%W$Ig%m$Ig$Ii(t$Ii$In%m$In$Io(t$Io$Ir%m$Ir$Is(t$Is$JW%m$JW$JY(t$JY&Fb%m&Fb&Ff(t&Ff;'S%m;'S;=`+r<%lO%mR2SOiQsPR2ZOhQsPR2bOfQsP~2gOd~R2nhpQrPOX){Z]){^p){tu){{|){!Q![){!_!`){!c!}){#O#P){#T#o){#q#r){#s$g){$h$q){$r$}){%O%R){%S%V){%W$Ig){$Ii$In){$Io$Ir){$Is$JW){$JY&Fb){&Ff;'S){;'S;=`+l<%lO){",
  tokenizers: [0, 1, 2],
  topRules: {"template":[0,1]},
  tokenPrec: 0
})
