# fly.toml app configuration file generated for frontend-icy-cloud-3590 on 2024-09-19T09:46:25+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'frontend-icy-cloud-3590'
primary_region = 'jnb'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[env]
PORT = "80"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

